// Testers
export const FETCH_TESTERS_REQUEST = 'FETCH_TESTERS_REQUEST'
export const FETCH_TESTERS_SUCCESS = 'FETCH_TESTERS_SUCCESS'
export const FETCH_TESTERS_NOT_FOUND = 'FETCH_TESTERS_NOT_FOUND'
export const FETCH_TESTERS_FAILED = 'FETCH_TESTERS_FAILED'
